name: Heapleak test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: crystallang/crystal:1.7
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: shards build

      - name: Test
        run: crystal spec
